version: 2

project_name: mast

builds:
  - main: ./cmd/mast
    binary: mast
    ldflags:
      - -s -w
      - -X github.com/brijorn/mast/internal/version.Version={{.Version}}
      - -X github.com/brijorn/mast/internal/version.Commit={{.Commit}}
      - -X github.com/brijorn/mast/internal/version.Date={{.Date}}
    goos:
      - android
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: android
        goarch: amd64

archives:
  - formats: ["tar.gz"]
    format_overrides:
      - goos: windows
        formats: ["zip"]
checksum:
  name_template: "checksums.txt"
